image: node:16-alpine
pages:
  tags:
    - ci
    - k8s
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add git
  script:
    - pnpm i
    - pnpm run build
  artifacts:
    paths:
      - public
  only:
    - main
